# Generated by Django 5.0.13 on 2025-11-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
