# Generated by Django 5.0.13 on 2025-12-03 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_latitude_cliente_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_interno',
            field=models.CharField(max_length=150),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='status',
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.statuscliente'),
        ),
    ]
