# Generated by Django 5.0.13 on 2025-12-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marcadormanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='instagram',
            field=models.URLField(blank=True, help_text='Link do Instagram da empresa', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Link do LinkedIn da empresa', null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
