# Generated by Django 5.0.13 on 2025-12-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente_instagram_cliente_linkedin_contato_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('executor', 'Executor de Piso'), ('construtora', 'Construtora'), ('concreteira', 'Concreteira'), ('outros', 'Outros')], max_length=20)),
                ('texto_gerado', models.TextField()),
                ('respostas_json', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_registros', to='core.cliente')),
            ],
        ),
    ]
