# Generated by Django 5.0.13 on 2025-12-23 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_crmregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos_clientes/')),
                ('nome_original', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.cliente')),
            ],
        ),
    ]
