# Generated by Django 5.0.13 on 2026-01-09 13:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_anexocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='WppContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(blank=True, default='', max_length=150)),
                ('empresa_texto', models.CharField(blank=True, default='', max_length=150)),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='WppChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=120, unique=True)),
                ('ultimo_texto', models.CharField(blank=True, default='', max_length=400)),
                ('ultima_data', models.DateTimeField(blank=True, null=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.wppcontato')),
            ],
        ),
        migrations.CreateModel(
            name='WppMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=120, unique=True)),
                ('direcao', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], max_length=10)),
                ('texto', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.wppchat')),
            ],
        ),
    ]
