# Generated by Django 5.0.13 on 2026-01-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_wppcontato_wppchat_wppmensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wppmensagem',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='wppcontato',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='WppChat',
        ),
        migrations.DeleteModel(
            name='WppMensagem',
        ),
        migrations.DeleteModel(
            name='WppContato',
        ),
    ]
