# Generated by Django 5.0.13 on 2026-01-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_wppmensagem_chat_remove_wppcontato_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='indicacao',
            field=models.ForeignKey(blank=True, help_text='Cliente que indicou este cadastro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_indicados', to='core.cliente'),
        ),
    ]
