# Generated by Django 5.0.13 on 2026-02-16 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='cliente',
        ),
        migrations.AddField(
            model_name='obra',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ObraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.obra')),
            ],
            options={
                'unique_together': {('obra', 'cliente')},
            },
        ),
        migrations.AddField(
            model_name='obra',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='obras', through='core.ObraCliente', to='core.cliente'),
        ),
    ]
