# Generated by Django 5.0.13 on 2026-02-24 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_obra_cliente_obra_complemento_obra_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigemCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='status',
        ),
        migrations.AddField(
            model_name='cliente',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.origemcliente'),
        ),
        migrations.DeleteModel(
            name='StatusCliente',
        ),
    ]
