# Generated by Django 5.0.13 on 2026-03-11 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_origemcliente_remove_cliente_status_cliente_origem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos_obras/')),
                ('nome_original', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.obra')),
            ],
        ),
    ]
