# Generated by Django 5.0.13 on 2026-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_anexoobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacoes_crm',
            field=models.TextField(blank=True, null=True),
        ),
    ]
