# Generated by Django 5.0.13 on 2026-05-08 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cliente_observacoes_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proposta', models.CharField(max_length=30)),
                ('cliente_nome_pdf', models.CharField(blank=True, max_length=180, null=True)),
                ('cnpj_pdf', models.CharField(max_length=20)),
                ('arquivo_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_pdf', to='core.cliente')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PropostaPDFItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proposta', models.CharField(max_length=30)),
                ('produto', models.CharField(max_length=180)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cnpj_faturamento', models.CharField(blank=True, max_length=20, null=True)),
                ('linha_produto', models.CharField(blank=True, max_length=30, null=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.propostapdf')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
