# Generated by Django 5.0.13 on 2026-06-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tipoatividade_crmatividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmatividade',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tipoatividade',
            name='texto_pronto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
