# Generated by Django 5.0.13 on 2026-06-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_crmatividade_texto_tipoatividade_texto_pronto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoatividade',
            name='tipo_atividade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
