# Generated by Django 5.0.13 on 2026-06-14 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tipoatividade_tipo_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCategoriaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='tipoatividade',
            name='tipo_atividade',
        ),
        migrations.AddField(
            model_name='crmatividade',
            name='tipo_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_atividades', to='core.tipocategoriaatividade'),
        ),
    ]
